# ===========================
# Globale Parameter
# ===========================

venue: "BINANCE"

# Instrumente
instruments:
  - instrument_id: "ERAUSDT-PERP.BINANCE"
    bar_types: 
      - "ERAUSDT-PERP.BINANCE-5-MINUTE-LAST-EXTERNAL"
    trade_size_usdt: "100"
  - instrument_id: "PUMPUSDT-PERP.BINANCE"
    bar_types: 
      - PUMPUSDT-PERP.BINANCE-5-MINUTE-LAST-EXTERNAL
    trade_size_usdt: "100"


# Backtest-Zeitraum
start_date: "2024-10-01T00:00:00Z"
end_date: "2025-10-31T00:00:00Z"

# Account/Venue-Parameter
starting_account_balance: "100000 USDT"
base_currency: "USDT"
account_type: "MARGIN"
oms_type: "NETTING"

# Risiko-Parameter (global)
trade_size_usdt: 1000
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000
close_positions_on_stop: [true]

# Visualisierung
visualise_qs: false

# ===========================
# Strategie-spezifische Parameter
# ===========================

# RSI-Strategie
rsi_period: [10,20]
rsi_overbought: [0.75,0.6]
rsi_oversold: [0.25,0.4]
