# in here will be the yaml for the 14 day listing short strategy
strategy_path: "strategies.coin_short_strategy:CoinShortStrategy"
config_path: "strategies.coin_short_strategy:CoinShortConfig"

visualize: true
venue: "BINANCE"

# automatic import from csv:
instruments_from_path:
  path: "../data/DATA_STORAGE/project_future_scraper/new_binance_perpetual_futures.csv"
  symbol_column: "symbol"
  instrument_suffix: "-PERP"
  bar_type_endings:
    - "-15-MINUTE-LAST-EXTERNAL"
  trade_size_usdt: "150"
  test: 2

data_sources:
  # Standard Bar-Daten: nutzt automatisch alle bar_types aus den Instrumenten
  - data_cls: "nautilus_trader.model.data:Bar"
    instrument_ids: all
    bar_types: from_instruments

  # Custom MetricsData für alle Instrumente (client_id wird automatisch gesetzt)
  - data_cls: "data.download.crypto_downloads.custom_class.metrics_data:MetricsData"
    instrument_ids: all

# Backtest-Zeitraum
start_date: "2024-01-01T00:00:00Z"
end_date: "2024-11-28T00:00:00Z"

# Account/Venue-Parameter
starting_account_balance: "10000 USDT"
base_currency: "USDT"
account_type: "MARGIN"
oms_type: "NETTING"

# Risiko-Parameter (global)
trade_size_usdt: 1000
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000
close_positions_on_stop: [true]

# ===========================
# Strategie-spezifische Parameter
# ===========================

only_trade_rth: false

use_min_coin_filters:
  enabled: true
  min_price: 0.25
  min_24h_volume: 50000
  min_sum_open_interest_value: 1000000  # $1M minimum open interest value

use_trend_following_setup:
  enabled: true
  entry_trend_ema_period: 120
  min_bars_over_ema: 35
  min_bars_under_ema: 35
  sl_atr_multiple: 2
  atr_period: 14

use_metrics_trend_following:
  enabled: false
  short_min_extreme_reversal_topt_longshortratio: 0.3 # Do professionally after base strat runs
  long_min_extreme_reversal_topt_longshortratio: 0.3  # Exit when divergence decreases by this amount from maximum extreme

# use_top_detection_setup: false

