strategy_path: "strategies.coin_listing_short_strategy:CoinListingShortStrategy"
config_path: "strategies.coin_listing_short_strategy:CoinListingShortConfig"

visualize: true
venue: "BYBIT"

instruments:
  - instrument_id: "BTCUSDT-LINEAR.BYBIT"
    bar_types: 
      - "BTCUSDT-LINEAR.BYBIT-15-MINUTE-LAST-EXTERNAL"
    trade_size_usdt: "1"  
  - instrument_id: "SOLUSDT-LINEAR.BYBIT"
    bar_types: 
      - "SOLUSDT-LINEAR.BYBIT-15-MINUTE-LAST-EXTERNAL"
    trade_size_usdt: "1"
 

instruments_from_path:
  path: "../data/DATA_STORAGE/project_future_scraper/new_bybit_linear_perpetual_futures.csv"
  symbol_column: "symbol"
  instrument_suffix: "-LINEAR"
  bar_type_endings:
    - "-15-MINUTE-LAST-EXTERNAL"
  trade_size_usdt: "150"
  test: 2

data_sources:
  - data_cls: "nautilus_trader.model.data:Bar"
    instrument_ids: all
    bar_types: from_instruments

  - data_cls: "data.download.crypto_downloads.custom_class.bybit_metrics_data:BybitMetricsData"
    instrument_ids: all

  # - data_cls: "data.download.crypto_downloads.custom_class.fear_and_greed_data:FearAndGreedData"
  #   instrument_ids: 
  #     - "FNG-INDEX.BINANCE"

# backtest period
start_date: "2025-01-01T00:00:00Z"
end_date: "2025-02-01T00:00:00Z"

# account/venue params  
starting_account_balance: "1000 USDT"
base_currency: "USDT"
account_type: "MARGIN"
oms_type: "NETTING"

# risk params
close_positions_on_stop: true
min_account_balance: 1000

exp_growth_atr_risk:
  enabled: false
  atr_period: 20
  atr_multiple: 2.0
  risk_percent: 0.04

log_growth_atr_risk:
  enabled: true
  atr_period: 50
  atr_multiple: 3.0
  risk_percent: 0.05

exp_fixed_trade_risk:
  enabled: false
  invest_percent: 0.05 # percent of current account balance per trade (no sl calculation)

log_fixed_trade_risk:
  enabled: false
  investment_size: 50 # fixed USDT amount per trade

# ===========================
# Strategy-specific params
# ===========================
only_execute_short: true
hold_profit_for_remaining_days: false
time_after_listing_close: 22
max_leverage: 1

use_min_coin_filters:
  enabled: false
  min_price: 0.25
  min_24h_volume: 50000
  min_sum_open_interest_value: 1000000

use_aroon_simple_trend_system:
  enabled: true
  aroon_period: 70
  aroon_osc_short_threshold: -50

entry_scale_binance_metrics: # rank based approach for ENTRY logic
  enabled: false
  rolling_window_bars_binance: 200
  upper_percentile_threshold_binance: 95
  lower_percentile_threshold_binance: 5

exit_scale_binance_metrics: # rank based approach for EXIT logic  
  enabled: true
  rolling_window_bars_binance: 2000 # for OI around 2000 and for TopTrader around 500 best
  upper_percentile_threshold_binance: 95
  lower_percentile_threshold_binance: 5

five_day_scaling_filters:
  enabled: false
  amount_change_scaled_values: 250
  toptrader_short_threshold: 0.8
  toptrader_allow_entry_difference: 0.5
  oi_trade_threshold: 0.8
  oi_allow_entry_difference: 0.5

exit_l3_metrics_in_profit:
  enabled: true
  exit_amount_change_scaled_values: 100
  exit_toptrader_short_threshold: -0.95
  exit_toptrader_allow_difference: 0.8
  exit_oi_threshold: -0.95
  exit_oi_allow_difference: 0.8
  only_check_thresholds_after_entry: true
  exit_signal_mode: "oi_only"  # Options: "toptrader_only", "oi_only", "both_or", "both_and"

btc_performance_risk_scaling:
  enabled: false
  risk_scaling_method: "linear"
  rolling_zscore: 200
  stop_executing_above_zscore: 2.8
  max_zscore: 4.0
  min_zscore: -4.0
  risk_multiplier_max_z_threshold: 1.0 # 0.4
  risk_multiplier_min_z_threshold: 1.0 # 3.0

sol_performance_risk_scaling:
  enabled: false
  risk_scaling_method: "linear"
  rolling_zscore: 200
  stop_executing_above_zscore: 2.8
  max_zscore: 4.0
  min_zscore: -4.0
  risk_multiplier_max_z_threshold: 1.0 # 0.4
  risk_multiplier_min_z_threshold: 1.0 # 3.0


