# Instrument
symbol: "BTCUSDT-PERP"
venue: "BINANCE"
instrument_id: "BTCUSDT-PERP.BINANCE"
bar_type: "BTCUSDT-PERP.BINANCE-5-MINUTE-LAST-EXTERNAL"

# Backtest-Zeitraum
start_date: "2024-10-01T00:00:00Z"
end_date: "2024-10-31T00:00:00Z"

# Strategie-Parameter
fvg_min_size: 0.0005
fvg_lookback: 3

# Risk-Parameter
trade_size: [0.5]
close_positions_on_stop: [true]
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000
risk_reward_ratio: [0.5, 1, 1.5, 2, 2.5, 3, 3.5]

# Account/Venue-Parameter
starting_account_balance: "100000 USDT"
base_currency: "USDT"
account_type: "MARGIN"
oms_type: "NETTING"