# Instrument
symbol: "VOO"
venue: "ARCA"
instrument_id: "VOO.ARCA"
bar_type: "VOO.ARCA-1-DAY-LAST-EXTERNAL"


# Backtest-Zeitraum
start_date: "2012-01-01T00:00:00Z"
end_date: "2024-12-30T23:59:59Z"

# Strategie-Parameter
kalman_process_var: 0.00001
kalman_measurement_var: 0.01
kalman_window: 10
vwap_lookback: [20]
zscore_window: [20]
vwap_zscore_entry_long: [-2.1]
vwap_zscore_entry_short: [2.3]

# Risk-Parameter
trade_size_usd: 10000
close_positions_on_stop: true
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000

 
# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"

# Durchlaufzeit ohne GARCH 1 Parameterset: 8 Sekunden