# Instrument & Daten
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type_5m: "SPY.ARCA-5-MINUTE-LAST-EXTERNAL"
start_date: "2024-01-01T00:00:00Z"
end_date: "2024-12-01T23:59:59Z"

# BAAsis - Params (hier drunter sind die Starteinstellungen)
base_parameters:
  kalman_exit_process_var: 0.0000001
  kalman_exit_measurement_var: 0.001
  kalman_exit_zscore_window: 20

  vwap:
    vwap_anchor_on_kalman_cross: true 
    vwap_require_trade_for_reset: true 
    vwap_min_bars_for_zscore: 15
    vwap_reset_grace_period: 40

  elastic_entry:
    zscore_long_threshold: -2.0
    zscore_short_threshold: 2.0
    recovery_delta: 1.0
    allow_multiple_recoveries: true
    recovery_cooldown_bars: 5
    alllow_stacking: true
    max_stacked_positions: 3
    additional_zscore_min_gain: 1.5
    recovery_delta_reentry: 1.0
    stacking_bar_cooldown: 20
  
  kalman_exit_long: 0
  kalman_exit_short: 0 

  long_risk_factor: 1
  short_risk_factor: 1

# these will be calculated while Runnninnng and then netted with base params
adaptive_factors:
  kalman: 
    enabled: true
    process_var: 0.000001
    measurement_var: 0.001 
  
  slope: # the stats we are changing below are the outer borders for the multiplication, which will be scaled linearlly
    enabled: true
    min: 0.5
    max: 2.0
    sensitivity: 0.1 # WICHTIG: An echte Slope-Range angepasst (statt 5)
  
  atr: # the ATR weighting only depends on the atr precentile window -> only enable to see if ATR is not redundant
    enabled: true
    window: 14
    percentile_window: 200 # how many of the last ATR-values are being used for perecentile- calculation
    outlier_threshold: 3.0 # Sigma - threshold (based on winsorizing) -> prevents distortion from big gaps, jumps...
    min: 0.4 
    max: 2.5 
  
  combination: # if set to true - we don´t just multiply atr and the slope, but combine them logarithmically
    use_log_space: true
    min_combined_factor: 0.2 # 1 is the base - factor
    max_combined_factor: 5.0

  asymmetric_offset:
    enabled: false
    max_offset_pct: 0.5 
    min_trend_strength: 0.005  # Sehr niedrig für kleine Slopes
    strength_threshold: 0.1   # Niedrigere Schwelle für echte Slope-Range
    scale_by_volatility: true
    vol_sensitivity: 0.5  
    
  linear_adjustments:
    trend_sensitivity: 0.6
    vol_sensitivity: 0.8
    max_trend_strength: 0.6
  
  slope_monitor:
    enabled: true
    bin_size: 0.001

gap_threshold_pct: 0.2
vix_fear_threshold: 38

# Risk-Parameter
invest_percent: 1.5
close_positions_on_stop: true
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000

# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"