# Instrument
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type: "SPY.ARCA-1-DAY-LAST-EXTERNAL"
bar_type_1h: "SPY.ARCA-1-HOUR-LAST-EXTERNAL"

# Backtest-Zeitraum
start_date: "2008-01-01T00:00:00Z"
end_date: "2024-09-30T23:59:59Z"

# Strategie-Parameter
kalman_process_var: 0.00001
kalman_measurement_var: 0.01
kalman_window: 10
vwap_lookback: [35]
zscore_window: [35]
vwap_zscore_entry_long: [-1.6]
vwap_zscore_entry_short: [2]

# Risk-Parameter
trade_size_usd: 200000
close_positions_on_stop: true
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000

 
# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"
