symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type_5m: "SPY.ARCA-5-MINUTE-LAST-EXTERNAL"
start_date: "2023-10-01T00:00:00Z"
end_date: "2024-12-01T23:59:59Z"

only_trade_rth: true

base_parameters:
  kalman_process_var: 0.00000001
  kalman_measurement_var: 0.01
  kalman_zscore_window: 15

  vwap:
    vwap_anchor_on_kalman_cross: true 
    vwap_require_trade_for_reset: true 
    vwap_min_bars_for_zscore: 25
    vwap_reset_grace_period: 25

  elastic_entry:
    zscore_long_threshold: -3.5
    zscore_short_threshold: 4.5
    recovery_delta: 0.6
    allow_multiple_recoveries: true
    recovery_cooldown_bars: 10
    alllow_stacking: true
    max_long_stacked_positions: 5
    max_short_stacked_positions: 2
    additional_zscore_min_gain: 2.5
    recovery_delta_reentry: 0.9
    stacking_bar_cooldown: 10
  
  adaptive_exit:
    enabled: true
    extension_threshold: 1.5
    long_base_exit: 0.02
    long_max_extension: 1.5
    short_base_exit: 0.02
    short_max_extension: 1.0

  long_risk_factor: 1.2
  short_risk_factor: 0.8

adaptive_factors:
  slope:
    enabled: true
    min: 0.3
    max: 3.5
    sensitivity: 0.02
  
  atr:
    enabled: true
    window: 14
    percentile_window: 600
    outlier_threshold: 2.0
    min: 0.4
    max: 2.8
  
  combination:
    use_log_space: true
    min_combined_factor: 0.5
    max_combined_factor: 2.0

  asymmetric_offset:
    enabled: true
    max_offset_pct: 1.8
    min_trend_strength: 0.1
    strength_threshold: 0.6
    scale_by_volatility: true
    vol_sensitivity: 0.75
    
  linear_adjustments:
    trend_sensitivity: 0.6
    vol_sensitivity: 0.35
    max_trend_strength: 1.0
  
  slope_monitor:
    enabled: true
    bin_size: 0.0003

gap_threshold_pct: 0.8
vix_fear_threshold: 38

invest_percent: 3.0
close_positions_on_stop: true
risk_percent: 0.02
max_leverage: 2.5
min_account_balance: 1000

starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"