# Instrument
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type: "SPY.ARCA-1-DAY-LAST-EXTERNAL"
bar_type_1h: "SPY.ARCA-1-HOUR-LAST-EXTERNAL"

# Backtest-Zeitraum
start_date: "2008-01-01T00:00:00Z"
end_date: "2024-09-30T23:59:59Z"

# Strategie-Parameter
kalman_process_var: 0.00001
kalman_measurement_var: 0.01
kalman_window: 10

vwap_lookback: [40]
zscore_window: [40]

kalman_slope_sector_params:
  strong_down:
    allow_trades: true
    long_risk_factor: 0.5
    short_risk_factor: 1.5
    regime_params:
      regime1:
        zscore_entry_long: -1.6
        zscore_entry_short: 1.8
        zscore_pre_entry_long: -2.0
        zscore_pre_entry_short: 2.2
        zscore_exit_long: 0.0
        zscore_exit_short: 0.5
      regime2:
        zscore_entry_long: -2.3
        zscore_entry_short: 2.4
        zscore_pre_entry_long: -2.6
        zscore_pre_entry_short: 2.8
        zscore_exit_long: 0.0
        zscore_exit_short: 0.5
  moderate_down:
    allow_trades: true
    long_risk_factor: 0.8
    short_risk_factor: 1.2
    regime_params:
      regime1:
        zscore_entry_long: -1.5
        zscore_entry_short: 2.5
        zscore_pre_entry_long: -2.2
        zscore_pre_entry_short: 2.7
        zscore_exit_long: 0.1
        zscore_exit_short: 0.6
      regime2:
        zscore_entry_long: -2.0
        zscore_entry_short: 2.7
        zscore_pre_entry_long: -2.4
        zscore_pre_entry_short: 2.9
        zscore_exit_long: 0.1
        zscore_exit_short: 0.6
  sideways:
    allow_trades: true
    long_risk_factor: 1.0
    short_risk_factor: 1.0
    regime_params:
      regime1:
        zscore_entry_long: -1.3
        zscore_entry_short: 2.2
        zscore_pre_entry_long: -1.8
        zscore_pre_entry_short: 2.4
        zscore_exit_long: 0.2
        zscore_exit_short: 0.7
      regime2:
        zscore_entry_long: -1.6
        zscore_entry_short: 2.4
        zscore_pre_entry_long: -2.0
        zscore_pre_entry_short: 2.7
        zscore_exit_long: 0.2
        zscore_exit_short: 0.7
  moderate_up:
    allow_trades: true
    long_risk_factor: 1.2
    short_risk_factor: 0.8
    regime_params:
      regime1:
        zscore_entry_long: -1.2
        zscore_entry_short: 2.4
        zscore_pre_entry_long: -1.6
        zscore_pre_entry_short: 2.2
        zscore_exit_long: 0.3
        zscore_exit_short: 0.8
      regime2:
        zscore_entry_long: -1.4
        zscore_entry_short: 2.6
        zscore_pre_entry_long: -1.8
        zscore_pre_entry_short: 2.4
        zscore_exit_long: 0.3
        zscore_exit_short: 0.8
  strong_up:
    allow_trades: true
    long_risk_factor: 1.5
    short_risk_factor: 0.5
    regime_params:
      regime1:
        zscore_entry_long: -1.0
        zscore_entry_short: 2.6
        zscore_pre_entry_long: -1.4
        zscore_pre_entry_short: 2.0
        zscore_exit_long: 0.4
        zscore_exit_short: 0.9
      regime2:
        zscore_entry_long: -1.2
        zscore_entry_short: 2.8
        zscore_pre_entry_long: -1.6
        zscore_pre_entry_short: 2.2
        zscore_exit_long: 0.4
        zscore_exit_short: 0.9

vix_fear_threshold: 35.0
vix_chill_threshold: 22.0

# garch_window: 750         
# garch_p: 1                
# garch_q: 1                
# garch_vola_quantile: 0.8

# Risk-Parameter
invest_percent: 0.6
close_positions_on_stop: true
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000

 
# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"