# Instrument
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type_1h: "SPY.ARCA-1-HOUR-LAST-EXTERNAL"
bar_type_5m: "SPY.ARCA-5-MINUTE-LAST-EXTERNAL"

# Backtest-Zeitraum
start_date: "2022-01-01T00:00:00Z"
end_date: "2023-09-01T23:59:59Z"

# Neue Kalman-Parameter für Exit-Z-Score
kalman_exit_process_var: [0.00000001]
kalman_exit_measurement_var: [0.01]
kalman_exit_window: 10
kalman_exit_zscore_window: [30]
 
# Kalmanf für regime:
kalman_process_var: [0.0000005]
kalman_measurement_var: [0.01]
kalman_window: 10
kalman_disable_price_condition_slope_long: 0.04
kalman_disable_price_condition_slope_short: 0.04
kalman_slope_thresholds:
  strong_down: -0.1
  moderate_down: -0.03
  sideways: 0.03
  moderate_up: 0.1

vwap_lookback: [512]
zscore_window: [512]
gap_threshold_pct: 0.1

kalman_slope_sector_params:
  strong_down:
    allow_trades: true
    long_risk_factor: 0.5 
    short_risk_factor: 1.5 
    regime_params:
      regime1:
        zscore_entry_long: -1.9
        zscore_entry_short: 1.1
        zscore_pre_entry_long: -2.2
        zscore_pre_entry_short: 1.4 
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
      regime2:
        zscore_entry_long: -2.3 
        zscore_entry_short: 1.5 
        zscore_pre_entry_long: -2.6 
        zscore_pre_entry_short: 1.8 
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0

  moderate_down:
    allow_trades: true
    long_risk_factor: 0.8 
    short_risk_factor: 1.2
    regime_params:
      regime1:
        zscore_entry_long: -1.7 
        zscore_entry_short: 1.3 
        zscore_pre_entry_long: -2.0 
        zscore_pre_entry_short: 1.6
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
      regime2:
        zscore_entry_long: -2.3 
        zscore_entry_short: 1.7 
        zscore_pre_entry_long: -2.4 
        zscore_pre_entry_short: 2.0 
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0

  sideways:
    allow_trades: true
    long_risk_factor: 1.0
    short_risk_factor: 1.0
    regime_params:
      regime1:
        zscore_entry_long: -1.5
        zscore_entry_short: 1.5
        zscore_pre_entry_long: -1.9
        zscore_pre_entry_short: 1.9
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
      regime2:
        zscore_entry_long: -1.9
        zscore_entry_short: 1.9
        zscore_pre_entry_long: -2.2
        zscore_pre_entry_short: 2.2
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0

  moderate_up:
      allow_trades: true
      long_risk_factor: 1.2
      short_risk_factor: 0.8
      regime_params:
        regime1:
          zscore_entry_long: -1.3
          zscore_entry_short: 1.7
          zscore_pre_entry_long: -1.5
          zscore_pre_entry_short: 2.0
          kalman_zscore_exit_long: 0
          kalman_zscore_exit_short: 0
        regime2:
          zscore_entry_long: -1.7
          zscore_entry_short: 2.1
          zscore_pre_entry_long: -2.0
          zscore_pre_entry_short: 2.4
          kalman_zscore_exit_long: 0
          kalman_zscore_exit_short: 0

  strong_up:
      allow_trades: true
      long_risk_factor: 1.5
      short_risk_factor: 0.5
      regime_params:
        regime1:
          zscore_entry_long: -1.1
          zscore_entry_short: 1.9
          zscore_pre_entry_long: -1.4
          zscore_pre_entry_short: 2.2
          kalman_zscore_exit_long: 0
          kalman_zscore_exit_short: 0
        regime2:
          zscore_entry_long: -1.5
          zscore_entry_short: 2.3
          zscore_pre_entry_long: -1.8
          zscore_pre_entry_short: 2.6
          kalman_zscore_exit_long: 0
          kalman_zscore_exit_short: 0

vix_fear_threshold: [38]
vix_chill_threshold: [22]

# Risk-Parameter
invest_percent: 1.5
close_positions_on_stop: true
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000

 
# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"