symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type_5m: "SPY.ARCA-5-MINUTE-LAST-EXTERNAL"
start_date: "2021-10-01T00:00:00Z"
end_date: "2022-08-01T23:59:59Z"

only_trade_rth: true

base_parameters:
  kalman_process_var: 0.0000001
  kalman_measurement_var: 0.01
  kalman_zscore_window: 8

  vwap: # Anchor method options: "kalman_cross","daily", "weekly", "rolling" 
    anchor_method: "daily"
    vwap_require_trade_for_reset: true 
    vwap_min_bars_for_zscore: 20
    vwap_reset_grace_period: 40
    rolling_window_bars: 500  # only for rolling method

  elastic_entry:
    zscore_long_threshold: -2.8
    zscore_short_threshold: 3.2
    recovery_delta: 0.6
    long_min_distance_from_kalman: -5
    short_min_distance_from_kalman: 5
    allow_multiple_recoveries: true
    recovery_cooldown_bars: 10
    alllow_stacking: true
    max_long_stacked_positions: 5
    max_short_stacked_positions: 2
    additional_zscore_min_gain: 1.5
    recovery_delta_reentry: 0.8
    stacking_bar_cooldown: 10

  # the following method get scaled only with slope and can use "linear", "exponential" and "logarithmic"
  slope_exit_scaling:
    enabled: true
    scaling_method: "logarithmic"
    base_long_exit: 5.0
    base_short_exit: -5.0
    max_long_exit_uptrend: 20.0
    max_long_exit_downtrend: 2.0
    max_short_exit_uptrend: -2.0
    max_short_exit_downtrend: -20.0

  slope_risk_scaling:
    enabled: true
    scaling_method: "logarithmic"
    base_long_risk: 1.0
    base_short_risk: 1.0
    max_long_risk_uptrend: 2.0
    max_long_risk_downtrend: 0.1
    max_short_risk_uptrend: 0.1
    max_short_risk_downtrend: 2.0

  slope_asymmetric_offset:
    enabled: true
    scaling_method: "linear"
    base_offset: 0.0
    max_offset_uptrend: 1.8
    max_offset_downtrend: -1.8

adaptive_factors:
  slope:
    enabled: true
    min: 0.5
    max: 1.4
    sensitivity: 0.04
  
  atr:
    enabled: true
    window: 14
    percentile_window: 600
    outlier_threshold: 2.0
    min: 0.5
    max: 1.8
  
  combination:
    use_log_space: true
    min_combined_factor: 0.6
    max_combined_factor: 2.0
  
  slope_monitor:
    enabled: true
    bin_size: 0.0005

gap_threshold_pct: 0.8
vix_fear_threshold: 38

invest_percent: 3.0
close_positions_on_stop: true
risk_percent: 0.02
max_leverage: 2.5
min_account_balance: 1000

starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"
