# Instrument & Daten
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type_5m: "SPY.ARCA-5-MINUTE-LAST-EXTERNAL"
start_date: "2023-06-01T00:00:00Z"
end_date: "2023-12-01T23:59:59Z"

# BAAsis - Params (hier drunter sind die Starteinstellungen)
base_parameters:
  kalman_exit_process_var: 0.0000001
  kalman_exit_measurement_var: 0.001
  kalman_exit_zscore_window: 20

  vwap:
    vwap_anchor_on_kalman_cross: true 
    vwap_require_trade_for_reset: true 
    vwap_min_bars_for_zscore: 15
    vwap_reset_grace_period: 40

  elastic_entry:
    zscore_long_threshold: -2.0
    base_zscore_short_threshold: 2.0
    recovery_delta: 1.0
    allow_multiple_recoveries: true
    recovery_cooldown_bars: 5
    alllow_stacking: true
    max_stacked_positions: 3
    additional_zscore_min_gain: 1.5
    recovery_delta_reentry: 1.0
    stacking_bar_cooldown: 20
  
  kalman_exit_long: 0
  kalman_exit_short: 0 

  long_risk_factor: 1
  short_risk_factor: 1

# these will be calculated while Runnninnng and then netted with base params
adaptive_factors:
  kalman: 
    enabled: true
    process_var: 0.000001
    measurement_var: 0.01 
  slope: 
    enabled: true
    min: 0.7
    max: 1.3
    sensitivity: 10
  atr: 
    enabled: true
    window: 14
    min: 0.7
    max: 1.5
  
  slope_monitor:
    enabled: true
    bin_size: 0.001
  
  linear_adjustments:
    trend_sensitivity: 0.3
    vol_sensitivity: 0.4
    max_trend_strength: 0.8

gap_threshold_pct: 0.2
vix_fear_threshold: 38
vix_chill_threshold: 22

# Risk-Parameter
invest_percent: 1.5
close_positions_on_stop: true
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000

# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"