# Instrument
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type: "SPY.ARCA-1-DAY-LAST-EXTERNAL"

# Strategie-Parameter
rsi_period: [10, 15, 20]
rsi_overbought: [0.75]
rsi_oversold: [0.25]
ttt_lookback: [10, 15]
ttt_atr_mult: [1.25, 1.5]
ttt_max_counter: [5, 10]

# Risk-Parameter
trade_size: [0.5]
close_positions_on_stop: [true]