
# Instrument
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type_1h: "SPY.ARCA-1-HOUR-LAST-EXTERNAL"
bar_type_5m: "SPY.ARCA-5-MINUTE-LAST-EXTERNAL"

# Backtest-Zeitraum
start_date: "2019-01-01T00:00:00Z"
end_date: "2021-9-01T23:59:59Z"

# Strategie-Parameter
kalman_process_var: [0.0000005]
kalman_measurement_var: [0.01]
kalman_window: 10
kalman_disable_price_condition_slope_long: 0.04
kalman_disable_price_condition_slope_short: 0.04
kalman_slope_thresholds:
  strong_down: -0.1
  moderate_down: -0.03
  sideways: 0.03
  moderate_up: 0.1

vix_fear_threshold: [40]
vix_chill_threshold: [22]

vwap_lookback: [700]
zscore_window: [156]

VSCBR_truerange_factor: 1.8
VSCBR_volume_factor: 1.2
VSCBR_zscore_threshold: 1.6
VSCBR_atr_window: 14
VSCBR_volume_window: 20
VSCBR_long_rel_close_threshold: 0.75
VSCBR_short_rel_close_threshold: 0.25

kalman_slope_sector_params:
  strong_down:
    allow_trades: true
    long_risk_factor: 0.6 
    short_risk_factor: 1.4 
    regime_params:
      regime1:
        zscore_condition_long: -2.6 
        zscore_condition_short: 2.0 
        zscore_exit_long: 0.0 
        zscore_exit_short: 0.0
      regime2:
        zscore_condition_long: -2.9
        zscore_condition_short: 2.3
        zscore_exit_long: 0.0 
        zscore_exit_short: 0.0 

  moderate_down:
    allow_trades: true
    long_risk_factor: 0.8 
    short_risk_factor: 1.2 
    regime_params:
      regime1:
        zscore_condition_long: -2.4 
        zscore_condition_short: 2.2
        zscore_exit_long: 0.0 
        zscore_exit_short: 0.0 
      regime2:
        zscore_condition_long: -2.7
        zscore_condition_short: 2.5 
        zscore_exit_long: 0.0 
        zscore_exit_short: 0.0 

  sideways:
    allow_trades: true
    long_risk_factor: 1.0
    short_risk_factor: 1.0
    regime_params:
      regime1:
        zscore_condition_long: -2.3 
        zscore_condition_short: 2.3 
        zscore_exit_long: 0.0 
        zscore_exit_short: 0.0 
      regime2:
        zscore_condition_long: -2.6
        zscore_condition_short: 2.6 
        zscore_exit_long: 0.0 
        zscore_exit_short: 0.0 

  moderate_up:
    allow_trades: true
    long_risk_factor: 1.2 
    short_risk_factor: 0.8
    regime_params:
      regime1:
        zscore_condition_long: -2.2 
        zscore_condition_short: 2.4 
        zscore_exit_long: 0.0 
        zscore_exit_short: 0.0 
      regime2:
        zscore_condition_long: -2.5 
        zscore_condition_short: 2.7 
        zscore_exit_long: 0.0 
        zscore_exit_short: 0.0  

  strong_up:
    allow_trades: true
    long_risk_factor: 1.4
    short_risk_factor: 0.6
    regime_params:
      regime1:
        zscore_condition_long: -2.0 
        zscore_condition_short: 2.6 
        zscore_exit_long: 0.0
        zscore_exit_short: 0.0
      regime2:
        zscore_condition_long: -2.3 
        zscore_condition_short: 2.9 
        zscore_exit_long: 0.0
        zscore_exit_short: 0.0

# Risk-Parameter
invest_percent: 0.8
close_positions_on_stop: true
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000

 
# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"