# hier rein kommt ähnlich wie strategie in mean_5m_regimes abgesehen vonnn:
# wir ändern die entry Logik sodass wir kein prev Zscore oder so haben,
# sondern einfach sagen wir möchten dann ab dieser Schwelle einen ChoCh z.B. haben
# auch BOS - Break of strucutre genannt

# Instrument
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type_1h: "SPY.ARCA-1-HOUR-LAST-EXTERNAL"
bar_type_5m: "SPY.ARCA-5-MINUTE-LAST-EXTERNAL"

# Backtest-Zeitraum
start_date: "2010-01-01T00:00:00Z"
end_date: "2020-10-01T23:59:59Z"

# Strategie-Parameter
kalman_process_var: [0.000001]
kalman_measurement_var: [0.01]
kalman_window: 10
kalman_disable_price_condition_slope_long: 0.025
kalman_disable_price_condition_slope_short: 0.025
kalman_slope_thresholds:
  strong_down: -0.1
  moderate_down: -0.03
  sideways: 0.03
  moderate_up: 0.1

vwap_lookback: [156]
zscore_window: [234]

kalman_slope_sector_params:
  strong_down:
    allow_trades: true
    long_risk_factor: 0.6 
    short_risk_factor: 1.8 
    regime_params:
      regime1:
        zscore_condition_long: -2.0 
        zscore_condition_short: 1.8 
        zscore_exit_long: -0.1 
        zscore_exit_short: 0.5 
      regime2:
        zscore_condition_long: -2.6 
        zscore_condition_short: 2.4 
        zscore_exit_long: -0.1 
        zscore_exit_short: 0.5 

  moderate_down:
    allow_trades: true
    long_risk_factor: 0.6 
    short_risk_factor: 1.1 
    regime_params:
      regime1:
        zscore_condition_long: -1.8 
        zscore_condition_short: 2.5
        zscore_exit_long: 0.0 
        zscore_exit_short: 0.6 
      regime2:
        zscore_condition_long: -2.3
        zscore_condition_short: 2.7 
        zscore_exit_long: 0.0 
        zscore_exit_short: 0.6 

  sideways:
    allow_trades: true
    long_risk_factor: 1.0
    short_risk_factor: 1.0
    regime_params:
      regime1:
        zscore_condition_long: -1.3 
        zscore_condition_short: 2.2 
        zscore_exit_long: 0.1 
        zscore_exit_short: 0.7 
      regime2:
        zscore_condition_long: -1.9
        zscore_condition_short: 2.4 
        zscore_exit_long: 0.1 
        zscore_exit_short: 0.7 

  moderate_up:
    allow_trades: true
    long_risk_factor: 1.0 
    short_risk_factor: 0.7
    regime_params:
      regime1:
        zscore_condition_long: -1.4 
        zscore_condition_short: 2.2 
        zscore_exit_long: 0.2 
        zscore_exit_short: 0.8 
      regime2:
        zscore_condition_long: -1.6 
        zscore_condition_short: 2.6 
        zscore_exit_long: 0.2 
        zscore_exit_short: 0.8  

  strong_up:
    allow_trades: true
    long_risk_factor: 1.8
    short_risk_factor: 0.6
    regime_params:
      regime1:
        zscore_condition_long: -1.2 
        zscore_condition_short: 2.6 
        zscore_exit_long: 0.3
        zscore_exit_short: 0.9
      regime2:
        zscore_condition_long: -1.4 
        zscore_condition_short: 2.8 
        zscore_exit_long: 0.3
        zscore_exit_short: 0.9

vix_fear_threshold: [40]
vix_chill_threshold: [22]

# Risk-Parameter
invest_percent: 1.2
close_positions_on_stop: true
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000

 
# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"