# Instrument & Daten
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type_5m: "SPY.ARCA-5-MINUTE-LAST-EXTERNAL"
start_date: "2023-10-01T00:00:00Z"
end_date: "2024-12-01T23:59:59Z"

only_trade_rth: true

# BAAsis - Params (hier drunter sind die Starteinstellungen)
base_parameters:
  kalman_process_var: 0.000025
  kalman_measurement_var: 0.015
  kalman_zscore_window: 15

  vwap:
    vwap_anchor_on_kalman_cross: true 
    vwap_require_trade_for_reset: true 
    vwap_min_bars_for_zscore: 24
    vwap_reset_grace_period: 45

  elastic_entry:
    zscore_long_threshold: -3.2
    zscore_short_threshold: 3.2
    recovery_delta: 1.2
    allow_multiple_recoveries: false
    recovery_cooldown_bars: 6
    alllow_stacking: false
    max_stacked_positions: 3
    additional_zscore_min_gain: 1.2
    recovery_delta_reentry: 0.9
    stacking_bar_cooldown: 18
  
  adaptive_exit:
    enabled: true
    extension_threshold: 1.2
    long_base_exit: 0.01
    long_max_extension: 0.1
    short_base_exit: 0.01
    short_max_extension: 0.1

  long_risk_factor: 0.55
  short_risk_factor: 0.55

# these will be calculated while Runnninnng and then netted with base params
adaptive_factors:
  slope:
    enabled: true
    min: 0.95
    max: 1.15
    sensitivity: 0.06
  
  atr:
    enabled: true
    window: 14
    percentile_window: 390
    outlier_threshold: 3.0
    min: 0.95
    max: 1.20
  
  combination:
    use_log_space: true
    min_combined_factor: 0.95 
    max_combined_factor: 1.15

  asymmetric_offset:
    enabled: true
    max_offset_pct: 1.4
    min_trend_strength: 0.18
    strength_threshold: 0.40
    scale_by_volatility: true
    vol_sensitivity: 0.45
    
  linear_adjustments:
    trend_sensitivity: 0.15
    vol_sensitivity: 0.15
    max_trend_strength: 0.80
  
  slope_monitor:
    enabled: true
    bin_size: 0.0005

gap_threshold_pct: 0.8
vix_fear_threshold: 38

# Risk-Parameter
invest_percent: 2.0
close_positions_on_stop: true
risk_percent: 0.015
max_leverage: 2
min_account_balance: 1000

# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"