# Instrument & Daten
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type_5m: "SPY.ARCA-5-MINUTE-LAST-EXTERNAL"
start_date: "2023-01-01T00:00:00Z"
end_date: "2023-04-01T23:59:59Z"

# BAAsis - Params (hier drunter sind die Starteinstellungen)
base_parameters:
  kalman_process_var: 0.0000001
  kalman_measurement_var: 0.05  
  kalman_zscore_window: 15

  vwap:
    vwap_anchor_on_kalman_cross: true 
    vwap_require_trade_for_reset: true 
    vwap_min_bars_for_zscore: 10
    vwap_reset_grace_period: 40

  elastic_entry:
    zscore_long_threshold: -4.5
    zscore_short_threshold: 4.5
    recovery_delta: 1.5
    allow_multiple_recoveries: true
    recovery_cooldown_bars: 2
    alllow_stacking: true
    max_stacked_positions: 3
    additional_zscore_min_gain: 2.2
    recovery_delta_reentry: 1.2
    stacking_bar_cooldown: 20
  
  kalman_zscore_exit_long: -0.01
  kalman_zscore_exit_short: 0.9

  long_risk_factor: 1.0
  short_risk_factor: 1.0

# these will be calculated while Runnninnng and then netted with base params
adaptive_factors:
  slope:
    enabled: true
    min: 0.6
    max: 1.6
    sensitivity: 0.03
  
  atr:
    enabled: true
    window: 20
    percentile_window: 200
    outlier_threshold: 2.0
    min: 0.7
    max: 1.4
  
  combination:
    use_log_space: true
    min_combined_factor: 0.3
    max_combined_factor: 2.5

  asymmetric_offset:
    enabled: true
    max_offset_pct: 1.8
    min_trend_strength: 0.02
    strength_threshold: 0.15
    scale_by_volatility: true
    vol_sensitivity: 0.4
    
  linear_adjustments:
    trend_sensitivity: 0.4
    vol_sensitivity: 0.3
    max_trend_strength: 0.8
  
  slope_monitor:
    enabled: true
    bin_size: 0.001

gap_threshold_pct: 0.2
vix_fear_threshold: 38

# Risk-Parameter
invest_percent: 2.0
close_positions_on_stop: true
risk_percent: 0.015
max_leverage: 2
min_account_balance: 1000

# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"