# Instrument
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type_1h: "SPY.ARCA-1-HOUR-LAST-EXTERNAL"
bar_type_5m: "SPY.ARCA-5-MINUTE-LAST-EXTERNAL"

# Backtest-Zeitraum
start_date: "2024-01-01T00:00:00Z"
end_date: "2024-09-01T23:59:59Z"

# Neue Kalman-Parameter für Exit-Z-Score
kalman_exit_process_var: [0.00000001]
kalman_exit_measurement_var: [0.001]
kalman_exit_window: 10
kalman_exit_zscore_window: [20]
 
# Kalmanf für regime:
kalman_process_var: 0.00001
kalman_measurement_var: 0.01
kalman_window: 10
kalman_disable_price_condition_slope_long: 0.025
kalman_disable_price_condition_slope_short: 0.025
kalman_slope_thresholds:
  strong_down: -0.2
  moderate_down: -0.1
  sideways: 0.1
  moderate_up: 0.2

test_which_slope_params: true

vwap_anchor_on_kalman_cross: true       
vwap_zscore_mode: "atr"              
vwap_min_bars_for_zscore: 15
vwap_reset_grace_period: 30             # Separate Grace Period für VWAP-Resets
vwap_require_trade_for_reset: true      # Trade muss erfolgt sein vor erneutem Reset

# nur eine wird verwendet
zscore_calculation:
  simple:
    # Einfach: price - vwap 
    enabled: false
  atr:
    # (price - vwap) / ATR
    enabled: true
    atr_window: 14
  std:
    # (price - vwap) / std(price - vwap)
    enabled: false
    std_window: 20

gap_threshold_pct: 0.1

elastic_reversion_entry:
  enabled: true
  lookback_window: 15
  allow_multiple_recoveries: true
  recovery_cooldown_bars: 5

kalman_slope_sector_params:
  strong_down:
    allow_trades: true
    long_risk_factor: 1.0
    short_risk_factor: 1.5
    regime_params:
      regime1:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -2.5 
          z_max_threshold: 2.5
          recovery_delta: 0.4 
          reset_neutral_zone_long: -0.5
          reset_neutral_zone_short: 0.5
      regime2:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -3.0  
          z_max_threshold: 3.0
          recovery_delta: 0.6 
          reset_neutral_zone_long: -0.8
          reset_neutral_zone_short: 0.8

  moderate_down:
    allow_trades: true
    long_risk_factor: 1.0
    short_risk_factor: 1.2
    regime_params:
      regime1:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -2.0  
          z_max_threshold: 2.0
          recovery_delta: 0.4 
          reset_neutral_zone_long: -0.5
          reset_neutral_zone_short: 0.5
      regime2:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -2.5 
          z_max_threshold: 2.5
          recovery_delta: 0.6 
          reset_neutral_zone_long: -0.8
          reset_neutral_zone_short: 0.8

  sideways:
    allow_trades: true
    long_risk_factor: 1.0
    short_risk_factor: 1.0
    regime_params:
      regime1:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -1.5  
          z_max_threshold: 1.5
          recovery_delta: 0.4 
          reset_neutral_zone_long: -2.5
          reset_neutral_zone_short: 0.5
      regime2:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -2.0  
          z_max_threshold: 2.0
          recovery_delta: 0.6 
          reset_neutral_zone_long: -0.8
          reset_neutral_zone_short: 0.8

  moderate_up:
    allow_trades: true
    long_risk_factor: 1.2
    short_risk_factor: 1.0
    regime_params:
      regime1:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -2.0  
          z_max_threshold: 2.0
          recovery_delta: 0.4 
          reset_neutral_zone_long: -0.5
          reset_neutral_zone_short: 0.5
      regime2:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -2.5  
          z_max_threshold: 2.5
          recovery_delta: 0.6 
          reset_neutral_zone_long: -0.8
          reset_neutral_zone_short: 0.8

  strong_up:
    allow_trades: true
    long_risk_factor: 1.5
    short_risk_factor: 1.0
    regime_params:
      regime1:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -2.5  
          z_max_threshold: 2.5
          recovery_delta: 0.4 
          reset_neutral_zone_long: -0.5
          reset_neutral_zone_short: 0.5
      regime2:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -3.0  
          z_max_threshold: 3.0
          recovery_delta: 0.6 
          reset_neutral_zone_long: -0.8
          reset_neutral_zone_short: 0.8

vix_fear_threshold: [38]
vix_chill_threshold: [22]

# Risk-Parameter
invest_percent: 1.5
close_positions_on_stop: true
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000

 
# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"