# Instrument
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type: "SPY.ARCA-1-DAY-LAST-EXTERNAL"

# Backtest-Zeitraum
start_date: "2008-01-01T00:00:00Z"
end_date: "2024-12-30T23:59:59Z"

# Strategie-Parameter
kalman_process_var: 0.00001
kalman_measurement_var: 0.01
kalman_window: 10
vwap_lookback: [8, 10, 12]
zscore_window: [8, 10, 12]
vwap_zscore_entry_long: [-1.8, -2, -2.2]
vwap_zscore_entry_short: [2.2, 2.4, 2.6]

# GARCH-Parameter
garch_window: 750         
garch_p: 1                
garch_q: 1                
garch_vola_threshold: 2.5

# Risk-Parameter
trade_size: 5
close_positions_on_stop: true
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000


# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"
