# Instrument
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type_5m: "SPY.ARCA-5-MINUTE-LAST-EXTERNAL"

# Backtest-Zeitraum
start_date: "2024-05-01T00:00:00Z"
end_date: "2024-10-01T23:59:59Z"

# Regime-Kalman:
kalman_process_var: [0.00000004]
kalman_measurement_var: 0.001                     
kalman_window: 10                                 
kalman_disable_price_condition_slope_long: 0.025  
kalman_disable_price_condition_slope_short: 0.025 
kalman_slope_thresholds:
  strong_down: -0.025
  moderate_down: -0.012
  sideways: 0.012
  moderate_up: 0.025
test_which_slope_params: true

# Mean-Exit-Kalman:
kalman_exit_process_var: [0.00000002]
kalman_exit_measurement_var: 0.001             
kalman_exit_window: 10                           
kalman_exit_zscore_window: [20]             

# VWAP 
vwap_anchor_on_kalman_cross: true                 
vwap_zscore_mode: "simple"              
vwap_min_bars_for_zscore: 15
vwap_reset_grace_period: 40
vwap_require_trade_for_reset: true
zscore_calculation:
  simple:
    enabled: true
  atr:
    enabled: false
    atr_window: 14
  std:
    enabled: false
    std_window: 20

# GAP-handling
gap_threshold_pct: 0.2

# Entry-params
elastic_reversion_entry:
  enabled: true
  allow_multiple_recoveries: true
  recovery_cooldown_bars: 5
  allow_stacking:
    enabled: false
    max_stacked_positions: 3
    additional_zscore_min_gain: 3.0
    recovery_delta_reentry: 1.5
    stacking_bar_cooldown: 15

# VIX
vix_fear_threshold: [38]
vix_chill_threshold: [22]
kalman_slope_sector_params:
  strong_down:
    allow_trades: true
    long_risk_factor: 1
    short_risk_factor: 1
    regime_params:
      regime1:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -2.5
          z_max_threshold: 2.5
          recovery_delta: 1.0
          reset_neutral_zone_long: -0.5
          reset_neutral_zone_short: 0.5
      regime2:
        kalman_zscore_exit_long: 0.0
        kalman_zscore_exit_short: 0.0
        elastic_entry:
          z_min_threshold: -2.5
          z_max_threshold: 2.5
          recovery_delta: 1.5
          reset_neutral_zone_long: -0.8
          reset_neutral_zone_short: 0.8

  moderate_down:
    allow_trades: true
    long_risk_factor: 1
    short_risk_factor: 1
    regime_params:
      regime1:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -2.5
          z_max_threshold: 2.5
          recovery_delta: 1.0
          reset_neutral_zone_long: -0.5
          reset_neutral_zone_short: 0.5
      regime2:
        kalman_zscore_exit_long: 0.0
        kalman_zscore_exit_short: 0.0
        elastic_entry:
          z_min_threshold: -2.5
          z_max_threshold: 2.5
          recovery_delta: 1.5
          reset_neutral_zone_long: -0.8
          reset_neutral_zone_short: 0.8

  sideways:
    allow_trades: true
    long_risk_factor: 1
    short_risk_factor: 1
    regime_params:
      regime1:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -2.5
          z_max_threshold: 2.5
          recovery_delta: 1.0
          reset_neutral_zone_long: -0.5
          reset_neutral_zone_short: 0.5
      regime2:
        kalman_zscore_exit_long: 0.0
        kalman_zscore_exit_short: 0.0
        elastic_entry:
          z_min_threshold: -2.5
          z_max_threshold: 2.5
          recovery_delta: 1.5
          reset_neutral_zone_long: -0.8
          reset_neutral_zone_short: 0.8

  moderate_up:
    allow_trades: true
    long_risk_factor: 1
    short_risk_factor: 1
    regime_params:
      regime1:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -2.5
          z_max_threshold: 2.5
          recovery_delta: 1.0
          reset_neutral_zone_long: -0.5
          reset_neutral_zone_short: 0.5
      regime2:
        kalman_zscore_exit_long: 0.0
        kalman_zscore_exit_short: 0.0
        elastic_entry:
          z_min_threshold: -2.5
          z_max_threshold: 2.5
          recovery_delta: 1.5
          reset_neutral_zone_long: -0.8
          reset_neutral_zone_short: 0.8

  strong_up:
    allow_trades: true
    long_risk_factor: 1
    short_risk_factor: 1
    regime_params:
      regime1:
        kalman_zscore_exit_long: 0
        kalman_zscore_exit_short: 0
        elastic_entry:
          z_min_threshold: -2.5
          z_max_threshold: 2.5
          recovery_delta: 1.5
          reset_neutral_zone_long: -0.5
          reset_neutral_zone_short: 0.5
      regime2:
        kalman_zscore_exit_long: 0.0
        kalman_zscore_exit_short: 0.0
        elastic_entry:
          z_min_threshold: -2.5
          z_max_threshold: 2.5
          recovery_delta: 1.5
          reset_neutral_zone_long: -0.8
          reset_neutral_zone_short: 0.8

# Risk-Parameter
invest_percent: 1.5
close_positions_on_stop: true
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000

# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"