# Instrument
symbol: "SPY"
venue: "ARCA"
instrument_id: "SPY.ARCA"
bar_type: "SPY.ARCA-1-DAY-LAST-EXTERNAL"

# Backtest-Zeitraum
start_date: "2008-01-01T00:00:00Z"
end_date: "2024-12-30T23:59:59Z"

# Strategie-Parameter
rsi_period: [10, 15, 20]
rsi_overbought: [0.75]
rsi_oversold: [0.25]
ttt_lookback: [10, 15]
ttt_atr_mult: [1.25, 1.5]
ttt_max_counter: [5, 10]

# Risk-Parameter
# trade_size_usd: 1000
close_positions_on_stop: [true]
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000
risk_reward_ratio: 2

# Account/Venue-Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"
