# Instrument
symbol: "BTCUSDT-PERP"
venue: "BINANCE"
instrument_id: "BTCUSDT-PERP.BINANCE"
bar_types: "BTCUSDT-PERP.BINANCE-5-MINUTE-LAST-EXTERNAL"
tick_buffer_size: 1000

# Backtest-Zeitraum
start_date: "2024-10-01T00:00:00Z"
end_date: "2024-10-04T00:00:00Z"

# Strategie-Parameter
rsi_period: [10, 15, 20, 25, 30, 40]
rsi_overbought: [0.75]
rsi_oversold: [0.25]

# Risk-Parameter
trade_size: [0.5]
close_positions_on_stop: [true]
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000

# Account/Venue-Parameter
starting_account_balance: "100000 USDT"
base_currency: "USDT"
account_type: "MARGIN"
oms_type: "NETTING"