# ===========================
# Globale Parameter
# ===========================
strategy_path: "strategies.VWAP_trend_strategy:VWAPTrendStrategy"
config_path: "strategies.VWAP_trend_strategy:VWAPTrendStrategyConfig"

visualize: true
venue: "GLBX"

# Multi-Instrument Configuration
instruments:
  - instrument_id: "ESH4.GLBX"
    bar_types:
      - "ESH4.GLBX-1-MINUTE-LAST-EXTERNAL"
    trade_size_usdt: 1000
    test: 1

# Backtest-Zeitraum
start_date: "2024-01-01T00:00:00Z"
end_date: "2024-03-30T23:59:59Z"

# Account/Venue Parameter
starting_account_balance: "100000 USD"
base_currency: "USD"
account_type: "MARGIN"
oms_type: "NETTING"

# Risiko-Parameter (global)
risk_percent: 0.01
max_leverage: 10.0
min_account_balance: 1000.0
close_positions_on_stop: true

# ===========================
# VWAP Trend Strategy Parameters
# ===========================
only_trade_rth: true 

# determine trend/extremes
min_bars_vwap_extremes: 12
min_band_trend_long: 1.8   
min_band_trend_short: 1.8  

# Entries
entry_band_long: 0.0    
entry_band_short: 0.0

# ATR sh*t
sl_atr_multiplier: 2.5     
tp_atr_multiplier: 6.0      
atr_period: 14           
